Bài 3.1: 

In [1]:
import numpy as np

print("Phiên bản NumPy hiện tại:", np.__version__)

np.show_config()

Phiên bản NumPy hiện tại: 2.3.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openbla

c:\Users\TRANG\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


Bài 3.2:

In [2]:
import numpy as np 

arr = np.arange(10)  # Tạo mảng 
print("Các phần tử của arr:", arr)
print("Kiểu dữ liệu của arr:", arr.dtype)
print("Kích thước của arr:", arr.shape)

arr_odd = arr[arr % 2 == 1]    # Lọc các số lẻ
arr_even = arr[arr % 2 == 0]   # Lọc các số chẵn
print("Các phần tử lẻ (arr_odd):", arr_odd)
print("Các phần tử chẵn (arr_even):", arr_even)

arr_update1 = np.where(arr % 2 == 0, arr, 100)
print("arr_update1:", arr_update1)

Các phần tử của arr: [0 1 2 3 4 5 6 7 8 9]
Kiểu dữ liệu của arr: int64
Kích thước của arr: (10,)
Các phần tử lẻ (arr_odd): [1 3 5 7 9]
Các phần tử chẵn (arr_even): [0 2 4 6 8]
arr_update1: [  0 100   2 100   4 100   6 100   8 100]


Bài 3.3:

In [3]:
import numpy as np

arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])

arr_c = np.intersect1d(arr_a, arr_b)
print("arr_c (xuất hiện cả arr_a và arr_b):", arr_c)

arr_d = np.setdiff1d(arr_a, arr_b)
print("arr_d (chỉ xuất hiện trong arr_a):", arr_d)

arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print("arr_f (giá trị từ 5 đến 10):", arr_f)

arr_c (xuất hiện cả arr_a và arr_b): [2 4]
arr_d (chỉ xuất hiện trong arr_a): [1 3 5 6]
arr_f (giá trị từ 5 đến 10): [ 6  9 10  8  6]


Bài 3.4:

In [4]:
import numpy as np

arr_zeros = np.zeros(10, dtype=int)
arr_zeros[4] = 1  # Vị trí thứ 5 có index = 4
print("arr_zeros:", arr_zeros)

arr_h = np.arange(10, 25)
arr_h_reversed = arr_h[::-1]
print("arr_h đảo ngược:", arr_h_reversed)

arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0, 1])
arr_1 = arr_k[arr_k != 0]
print("arr_1 (khác 0):", arr_1)

arr_2 = np.append(arr_1, [10, 20])
print("arr_2 (thêm 10,20):", arr_2)

arr_3 = np.insert(arr_2, 5, 100)
print("arr_3 (thêm 100 tại index 5):", arr_3)

arr_4 = np.delete(arr_3, [0, 1, 2])
print("arr_4 (xóa index 0,1,2):", arr_4)

arr_zeros: [0 0 0 0 1 0 0 0 0 0]
arr_h đảo ngược: [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
arr_1 (khác 0): [1 2 8 2 1 3 5 1]
arr_2 (thêm 10,20): [ 1  2  8  2  1  3  5  1 10 20]
arr_3 (thêm 100 tại index 5): [  1   2   8   2   1 100   3   5   1  10  20]
arr_4 (xóa index 0,1,2): [  2   1 100   3   5   1  10  20]


Bài 3.5:

In [5]:
import numpy as np
height = [74, 70, 72, 73, 69, 75, 71, 68, 70, 72, 74, 69, 71, 70, 72, 73, 74, 70, 71, 72,
          73, 74, 69, 70, 71, 72, 73, 74, 70, 71, 72, 73, 69, 70, 71, 72, 73, 74, 70, 71,
          72, 73, 74, 70, 71, 72, 73, 74, 70, 71, 72, 73, 74, 70, 71, 72, 73, 74, 70, 71,
          72, 73, 74, 70, 71, 72, 73, 74, 70, 71, 72, 73, 74, 70, 71, 72, 73, 74, 70, 71,
          72, 73, 74, 70, 71, 72, 73, 74, 70, 71, 72, 73, 74, 70, 71, 72, 73, 74, 70, 71]

weight = [180, 165, 190, 200, 155, 210, 175, 160, 170, 185, 195, 158, 178, 168, 182, 192, 205, 173, 180, 188,
          198, 202, 159, 172, 176, 186, 196, 208, 170, 175, 182, 193, 160, 168, 177, 185, 195, 205, 172, 180,
          187, 194, 202, 170, 175, 182, 192, 200, 172, 178, 185, 195, 203, 175, 180, 185, 193, 200, 172, 178,
          184, 192, 200, 170, 176, 182, 190, 198, 172, 178, 184, 192, 200, 170, 176, 182, 190, 198, 172, 178,
          184, 192, 200, 170, 176, 182, 190, 198, 172, 178, 184, 192, 200, 170, 176, 182, 190, 198, 172, 178]


arr_height = np.array(height)
arr_weight = np.array(weight)

inch_to_m = 0.0254
arr_height_m = arr_height * inch_to_m

pound_to_kg = 0.453592
arr_weight_kg = arr_weight * pound_to_kg

arr_bmi = arr_weight_kg / (arr_height_m ** 2)

weight_index_50 = arr_weight_kg[50]
print("Cân nặng của cầu thủ ở vị trí index 50 (kg):", weight_index_50)

height_100_110 = arr_height_m[100:111]
print("Chiều cao các cầu thủ từ index 100 đến 110 (m):", height_100_110)

bmi_under_21 = arr_bmi[arr_bmi < 21]
print("Các cầu thủ có BMI < 21:", bmi_under_21)

avg_height = np.mean(arr_height_m)
avg_weight = np.mean(arr_weight_kg)
print("Chiều cao trung bình (m):", avg_height)
print("Cân nặng trung bình (kg):", avg_weight)

max_height = np.max(arr_height_m)
max_weight = np.max(arr_weight_kg)
print("Chiều cao lớn nhất (m):", max_height)
print("Cân nặng lớn nhất (kg):", max_weight)

max_height = np.max(arr_height_m)
max_weight = np.max(arr_weight_kg)
print("Chiều cao lớn nhất (m):", max_height)
print("Cân nặng lớn nhất (kg):", max_weight)

min_height = np.min(arr_height_m)
min_weight = np.min(arr_weight_kg)
print("Chiều cao nhỏ nhất (m):", min_height)
print("Cân nặng nhỏ nhất (kg):", min_weight)

Cân nặng của cầu thủ ở vị trí index 50 (kg): 83.91452
Chiều cao các cầu thủ từ index 100 đến 110 (m): []
Các cầu thủ có BMI < 21: []
Chiều cao trung bình (m): 1.824228
Cân nặng trung bình (kg): 83.25227568
Chiều cao lớn nhất (m): 1.905
Cân nặng lớn nhất (kg): 95.25431999999999
Chiều cao lớn nhất (m): 1.905
Cân nặng lớn nhất (kg): 95.25431999999999
Chiều cao nhỏ nhất (m): 1.7271999999999998
Cân nặng nhỏ nhất (kg): 70.30676


Bài 3.6:

In [6]:
import numpy as np

arr = np.full((3, 3), True)
print("Bước 1: arr 3x3 với True:\n", arr)

arr_ID = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_ID.reshape(3, 3)
# Đổi cột 1 <-> cột 3
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\nBước 2: Đổi cột 1 <-> cột 3:\n", arr_2D)

arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("\nBước 3: Đổi dòng 1 <-> dòng 2:\n", arr_2D)

arr_2D = arr_2D[::-1, :]
print("\nBước 4: Đảo ngược các dòng:\n", arr_2D)

arr_2D = arr_2D[:, ::-1]
print("\nBước 5: Đảo ngược các cột:\n", arr_2D)

arr_2D_null = np.array([
    [1, 2, 3, np.nan],
    [5, 6, 7, np.nan],
    [8, 9, np.nan, 10]
])
has_null = np.isnan(arr_2D_null).any()
print("\nBước 6: Có giá trị null không?", has_null)

arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\nBước 7: Thay null bằng 0:\n", arr_2D_null)

Bước 1: arr 3x3 với True:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

Bước 2: Đổi cột 1 <-> cột 3:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]

Bước 3: Đổi dòng 1 <-> dòng 2:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]

Bước 4: Đảo ngược các dòng:
 [[8 7 6]
 [2 1 0]
 [5 4 3]]

Bước 5: Đảo ngược các cột:
 [[6 7 8]
 [0 1 2]
 [3 4 5]]

Bước 6: Có giá trị null không? True

Bước 7: Thay null bằng 0:
 [[ 1.  2.  3.  0.]
 [ 5.  6.  7.  0.]
 [ 8.  9.  0. 10.]]


Bài 3.7:

In [8]:
import numpy as np

np_baseball = np.loadtxt("baseball_2D.txt")
print("Bước 0: Đã đọc file baseball_2D.txt")

print("Bước 1:")
print("Kiểu dữ liệu:", np_baseball.dtype)
print("Kích thước:", np_baseball.shape)

print("\nBước 2: Dòng thứ 50:", np_baseball[49])

np_weight = np_baseball[:, 1]
print("\nBước 3: np_weight:", np_weight)

print("\nBước 4: Chiều cao vận động viên thứ 124:", np_baseball[123, 0])

avg_height = np.mean(np_baseball[:, 0])
avg_weight = np.mean(np_baseball[:, 1])
print("\nBước 5:")
print("Chiều cao trung bình:", round(avg_height, 2), "inch")
print("Cân nặng trung bình:", round(avg_weight, 2), "pound")

correlation = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])[0, 1]
print("\nBước 6: Hệ số tương quan chiều cao - cân nặng:", round(correlation, 3))
if correlation > 0.5:
    print("Nhận xét: Có tương quan thuận mạnh giữa chiều cao và cân nặng.")
elif correlation > 0:
    print("Nhận xét: Có tương quan thuận yếu giữa chiều cao và cân nặng.")
elif correlation < -0.5:
    print("Nhận xét: Có tương quan nghịch mạnh giữa chiều cao và cân nặng.")
elif correlation < 0:
    print("Nhận xét: Có tương quan nghịch yếu giữa chiều cao và cân nặng.")
else:
    print("Nhận xét: Không có tương quan giữa chiều cao và cân nặng.")

Bước 0: Đã đọc file baseball_2D.txt
Bước 1:
Kiểu dữ liệu: float64
Kích thước: (200, 2)

Bước 2: Dòng thứ 50: [ 67. 195.]

Bước 3: np_weight: [197. 157. 193. 153. 228. 212. 170. 218. 223. 220. 151. 215. 182. 225.
 203. 208. 177. 199. 167. 233. 171. 249. 160. 219. 150. 206. 213. 248.
 216. 195. 163. 197. 192. 188. 216. 207. 185. 188. 246. 181. 236. 208.
 166. 204. 209. 230. 231. 208. 197. 195. 217. 239. 174. 156. 247. 217.
 237. 157. 207. 236. 225. 170. 200. 165. 211. 175. 247. 229. 210. 237.
 201. 247. 221. 241. 199. 211. 246. 155. 200. 164. 175. 243. 237. 215.
 198. 179. 180. 227. 208. 197. 157. 205. 176. 211. 177. 155. 188. 155.
 191. 202. 160. 247. 166. 186. 241. 163. 191. 184. 175. 181. 186. 192.
 225. 211. 174. 214. 200. 166. 180. 195. 157. 191. 213. 181. 200. 200.
 164. 238. 213. 201. 169. 210. 159. 162. 231. 190. 163. 207. 153. 205.
 225. 150. 159. 233. 198. 192. 189. 208. 224. 227. 193. 195. 207. 204.
 186. 154. 183. 209. 195. 188. 176. 246. 175. 241. 160. 206. 186. 209.
 189. 1

Bài 3.8:

In [10]:
import numpy as np

heights = [190, 175, 180, 185, 178, 192, 170, 177, 182, 176, 195, 168]
positions = ['GK', 'M', 'A', 'D', 'M', 'GK', 'D', 'A', 'M', 'D', 'GK', 'A']

# Lưu heights vào file heights.txt
with open("heights.txt", "w") as f:
    for h in heights:
        f.write(f"{h}\n")

# Lưu positions vào file positions.txt
with open("positions.txt", "w") as f:
    for p in positions:
        f.write(f"{p}\n")

print("Đã tạo file heights.txt và positions.txt với dữ liệu mẫu.")

with open("heights.txt", "r") as f:
    heights_list = [float(line.strip()) for line in f]

with open("positions.txt", "r") as f:
    positions_list = [line.strip() for line in f]

# Bước 1a: Tạo numpy array từ positions
np_positions = np.array(positions_list)
print("\nBước 1a: np_positions:", np_positions)
print("Kiểu dữ liệu np_positions:", np_positions.dtype)

# Bước 1b: Tạo numpy array từ heights
np_heights = np.array(heights_list, dtype=float)
print("\nBước 1b: np_heights:", np_heights)
print("Kiểu dữ liệu np_heights:", np_heights.dtype)

# Bước 2: Chiều cao trung bình
gk_mean_height = np_heights[np_positions == 'GK'].mean()
print("\nBước 2: Chiều cao trung bình GK:", round(gk_mean_height, 2))

# Bước 3: Chiều cao trung bình ngoại trừ GK
non_gk_mean_height = np_heights[np_positions != 'GK'].mean()
print("Bước 3: Chiều cao trung bình vị trí khác GK:", round(non_gk_mean_height, 2))

# Bước 4: Tạo mảng players với dtype phức hợp
players_dtype = np.dtype([('position', 'U5'), ('height', 'float')])
players = np.zeros(len(heights_list), dtype=players_dtype)
players['position'] = np_positions
players['height'] = np_heights
print("\nBước 4: Mảng players:\n", players)

# Bước 5: Sắp xếp players theo chiều cao
players_sorted = np.sort(players, order='height')
print("\nBước 5: Players sắp xếp theo chiều cao:\n", players_sorted)

# Vị trí cao nhất và thấp nhất
tallest = players_sorted[-1]
shortest = players_sorted[0]
print("\nVị trí cao nhất:", tallest['position'], "với chiều cao:", tallest['height'])
print("Vị trí thấp nhất:", shortest['position'], "với chiều cao:", shortest['height'])

Đã tạo file heights.txt và positions.txt với dữ liệu mẫu.

Bước 1a: np_positions: ['GK' 'M' 'A' 'D' 'M' 'GK' 'D' 'A' 'M' 'D' 'GK' 'A']
Kiểu dữ liệu np_positions: <U2

Bước 1b: np_heights: [190. 175. 180. 185. 178. 192. 170. 177. 182. 176. 195. 168.]
Kiểu dữ liệu np_heights: float64

Bước 2: Chiều cao trung bình GK: 192.33
Bước 3: Chiều cao trung bình vị trí khác GK: 176.78

Bước 4: Mảng players:
 [('GK', 190.) ('M', 175.) ('A', 180.) ('D', 185.) ('M', 178.) ('GK', 192.)
 ('D', 170.) ('A', 177.) ('M', 182.) ('D', 176.) ('GK', 195.) ('A', 168.)]

Bước 5: Players sắp xếp theo chiều cao:
 [('A', 168.) ('D', 170.) ('M', 175.) ('D', 176.) ('A', 177.) ('M', 178.)
 ('A', 180.) ('M', 182.) ('D', 185.) ('GK', 190.) ('GK', 192.)
 ('GK', 195.)]

Vị trí cao nhất: GK với chiều cao: 195.0
Vị trí thấp nhất: A với chiều cao: 168.0


Bài 3.9:

In [12]:
import pandas as pd

# Đọc dữ liệu
euro12 = pd.read_csv("euro2012.csv")

# In euro12: type, shape, columns
print(type(euro12))
print(euro12.shape)
print(euro12.columns)

print(euro12["Goals"])

print("Số đội:", euro12["Team"].nunique())

print(euro12.info())

discipline = euro12[["Team", "Yellow Cards", "Red Cards"]]
print(discipline)

discipline_sorted = discipline.sort_values(
    by=["Red Cards", "Yellow Cards"], 
    ascending=False
)
print(discipline_sorted)

print("Trung bình Yellow Cards:", euro12["Yellow Cards"].mean())

print(euro12[euro12["Goals"] > 6])

print(euro12[euro12["Team"].str.startswith("G")])

print(euro12.iloc[:, :7])

print(euro12.iloc[:, :-3])

print(euro12[["Team", "Goals", "Shooting Accuracy", "Yellow Cards", "Red Cards"]])

print(euro12[euro12["Team"].isin(["England", "Italy", "Russia"])]
      [["Team", "Shooting Accuracy"]])

<class 'pandas.core.frame.DataFrame'>
(16, 7)
Index(['Team', 'Goals', 'Shots on Target', 'Shots', 'Shooting Accuracy',
       'Yellow Cards', 'Red Cards'],
      dtype='object')
0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64
Số đội: 16
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Team               16 non-null     object
 1   Goals              16 non-null     int64 
 2   Shots on Target    16 non-null     int64 
 3   Shots              16 non-null     int64 
 4   Shooting Accuracy  16 non-null     object
 5   Yellow Cards       16 non-null     int64 
 6   Red Cards          16 non-null     int64 
dtypes: int64(5), object(2)
memory usage: 1.0+ KB
None
                   Team  Yellow Cards  Red Cards
0           